### ISSUE TITLE
fails to build with haskoin-core-0.4.0

### ISSUE THREAD

**Issue by juhp** [runeksvendsen/bitcoin-payment-channel#1]
I think bitcoin-payment-channel-0.2.2.0 fails to build with haskoin-core-0.4.0 (the 1.0 upperbound is probably a bit generous...).

src/Data/Bitcoin/PaymentChannel/Internal/Util.hs:96:30: error:
    Not in scope: data constructor ‘HT.Tx’
    Module ‘Network.Haskoin.Transaction’ does not export ‘Tx’.

src/Data/Bitcoin/PaymentChannel/Internal/Util.hs:97:5: error:
    Not in scope: data constructor ‘HT.Tx’
    Module ‘Network.Haskoin.Transaction’ does not export ‘Tx’.

src/Data/Bitcoin/PaymentChannel/Internal/Util.hs:99:23: error:
    Not in scope: data constructor ‘HT.Tx’
    Module ‘Network.Haskoin.Transaction’ does not export ‘Tx’.

src/Data/Bitcoin/PaymentChannel/Internal/Util.hs:106:17: error:
    Not in scope: data constructor ‘HT.Tx’
    Module ‘Network.Haskoin.Transaction’ does not export ‘Tx’.

**Comment by runeksvendsen** [comment]
Hello Jens

Thanks for letting me know about this. Right you are. I admit to not having spent a lot of time thinking about dependency version ranges so far. But I see now why it's necessary.

I have updated version 0.2.3.0 (on Hackage now) to limit `haskoin-core` to `< 0.4.0`, and all other dependencies to within their respective current major versions.

**Comment by juhp** [comment]
Maybe your bounds are too strict? Now:

binary-0.8.3.0 is out of bounds for:
- [ ] bitcoin-payment-channel-0.2.3.0 (>=0.7.0 && < 0.8.0). Rune K. Svendsen runesvend@gmail.com @runeks. @runeksvendsen

time-1.6.0.1 is out of bounds for:
- [ ] bitcoin-payment-channel-0.2.3.0 (>=1.5.0 && < 1.6.0). Rune K. Svendsen runesvend@gmail.com @runeks. @runeksvendsen

I was more hoping you could increase the upperbound for haskoin-core - is that a lot work?: I don't really want to hold it back for long.  Would it be better to disable bitcoin-payment-channel temporarily from Stackage Nightly until you can support latest haskoin. Though note we are hoping to release LTS 7 soon.

**Comment by runeksvendsen** [comment]
I've put up `bitcoin-payment-channel-0.2.3.1` on Hackage which ups the major version bounds for `binary` and `time`.

I haven't had a chance to look at what has changed between haskoin `0.3.1` and `0.4.0` yet. However, I will do that in the nearest future, and get back to you with either a patched `bitcoin-payment-channel` or a time frame (for the patch).

**Comment by runeksvendsen** [comment]
@juhp I have had a chance to look at haskoin 0.4.0, and one of the changes is that binary serialization is now handled by `cereal` rather than `binary`. I always wanted to use `cereal`, but I ended up using `binary` because haskoin did, so what I will probably end up doing is not support haskoin < 0.4.0 (so I don't have to support two binary serialization libraries). 

To get to the point: it will take a fair amount of time to migrate to haskoin 0.4.0, as the `binary` dependency also extends out into a few applications of mine that use `bitcoin-payment-channel`.

**Comment by juhp** [comment]
Thanks for looking into it. It seems currently bitcoin-payment-channel is the only consumer of haskoin-core in Stackage so probably it is okay for the time being, but hopefully eventually you plan to migrate to 0.4+.

**Comment by juhp** [comment]
http://packdeps.haskellers.com/reverse/haskoin-core

Dunno whether it helps to see how haskoin-node and haskoin-wallet do it.

**Comment by runeksvendsen** [comment]
I went ahead and did the work. Turns out there wasn't that much to do - `binary` and `cereal` are very similar. `bitcoin-payment-channel-0.3.0.1` is on Hackage now.

Side note: I've often wondered whether there were libraries other than this one that use `haskoin-core`, I'm glad to have found the answer.
